### PR TITLE
adjust output filenames

### LINKED ISSUE #10: update reference output file
With #9, the score generated seems similar to the one expected.
Now the reference output files stored in each of the PI should be updated.

### PR DESCRIPTION
**Pull request by aremazeilles**
fix #10 

I suggest another filenaming for the generated PI files, as you can see in the "Changes" sheet.
For sure, the stored reference files should have the same name.

### CODE REVIEW

**Comment by AdrianaTorres** [comment]
I agree all the PI filename changes except the walk ratio one. You suggested "walking_ratio" but I prefer "walk_ratio" because it is the original name of the PI. Can I change it and accept the pull request?

**Comment by aremazeilles** [comment]
I changed it to  `walk_ratio`

**Comment by aremazeilles** [comment]
Ready to be merged, once the ull_request / build is done with success

**Comment by aremazeilles** [comment]
I don't understand why the build fails, but I would suggest to merge, and then I will work on the fix, if needed.

**Pull request merged**
